import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import { Button, InputGroup, FormControl, Form  } from 'react-bootstrap'
import FormData from 'form-data';
import axios from 'axios';


export default function Upload() {
  const [file, setFile] = useState()
  const [imgHash, setImgHash] = useState('')
  const [metadataHash, setMetadataHash] = useState('')

  const handleImgFile=async (fileToHandle) =>{
    console.log('starting')
    const metadataJson = require('../public/metadata.json')

    if (fileToHandle === undefined) return;
    if (metadataJson === undefined) return;
    const formData = new FormData()

    formData.append("file", fileToHandle)
    
    const API_KEY = '130c2d4f5ee010a508d2'
    const API_SECRET = 'b5ff2c2ccb876d171aa213f48b3cb17c8b863c316ca9a14e1646a0a107a6ff4d'
    const url =  `https://api.pinata.cloud/pinning/pinFileToIPFS`

    const response = await axios.post(url, formData, {
                                                      maxContentLength: "Infinity",
                                                      headers: {
                                                          "Content-Type": `multipart/form-data;boundary=${formData._boundary}`, 
                                                          'pinata_api_key': API_KEY,
                                                          'pinata_secret_api_key': API_SECRET
                                                      }})

      if (response.status === 200) {
        // get the hash
        setImgHash(response.data.IpfsHash)
        const names = fileToHandle.name.split(".");
        metadataJson['name'] = fileToHandle.name
        metadataJson['image'] = 'ipfs://'+response.data.IpfsHash
        metadataJson['description'] = 'this file created at ' + new Date().toLocaleString();
        console.log(metadataJson)
        handleJsonFile(metadataJson, names[0])
      }
      
  }

  const handleJsonFile = async (metadataJson, name) =>{
    const API_KEY = '130c2d4f5ee010a508d2'
    const API_SECRET = 'b5ff2c2ccb876d171aa213f48b3cb17c8b863c316ca9a14e1646a0a107a6ff4d'
    const url =  `https://api.pinata.cloud/pinning/pinJSONToIPFS`
    const body = JSON.parse('{ "pinataMetadata" : {}, "pinataContent" : {} }')
    body['pinataMetadata'] = JSON.parse('{ "name" : "'+name+'.json" }')
    body['pinataContent'] = metadataJson
    
    console.log(body)
    
    const response = await axios.post(url, body, {
                                                      headers: {
                                                          'pinata_api_key': API_KEY,
                                                          'pinata_secret_api_key': API_SECRET,
                                                          'Content-Type': 'application/json'
                                                      }})

      console.log(response)

      if (response.status === 200) {
        // get the hash
        setMetadataHash(response.data.IpfsHash)
      }
      
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="App">
          <input type="file" onChange={(event)=>setFile(event.target.files[0])}/>
          <Button onClick={()=>handleImgFile(file)}>Pin</Button>
          {
            //  render the hash
            imgHash.length > 0 && <img height='200' src={`https://gateway.pinata.cloud/ipfs/${imgHash}`} alt='not loading'/>
          }
          <br></br>
          {metadataHash != '' ? 'you can mint : ' + metadataHash : null}
        </div>
      </main>
    </div>
  )
}
